### ISSUE TITLE
Can't pass options when using bayes.fromJson

### ISSUE THREAD

**Issue by drazik** [Wozacosta/classificator#4]
Hello,

I tried to use `bayes.fromJson` to instantiate a classifier from a JSON representation. But I need to pass a `tokenizer` option and it doesn't seem to be possible with it.

Actually, we need to set an `options` property on the JSON we pass to this function, but since it needs to be stringified, we can't pass a function.

There are two solutions to this : 

1. don't expect to get a stringified object as a parameter, but a real JavaScript object, so we can actually provide a `tokenizer` function in the options
2. add an `options` parameter which can be merged with the JSON data after it has been parsed

What do you think about it ? I can work on a solution and open a PR, but I would like to know which solution you prefer ;)

Thank you very much for your work.

**Comment by Wozacosta** [comment]
Hi  @drazik,

I was thinking of allowing object as parameters to bayes.fromJson, the best solution would be to test the input being passed to fromJson() and \:
- if it's a string, proceed as we did before (JSON.parse(input))
- if it's of type object, use that object directly.

By the way, have you tried : 

```
var revivedClassifier = bayes.fromJson(stateJson)
revivedClassifier.tokenizer = yourTokenizer;
```
?

**Comment by drazik** [comment]
Hello. Thank you for your quick answer !

I just tried what your proposed and it worked :+1:

Still I think you can be sweet if `fromJson` could work with both objets and JSON strings. I will do that and open a PR ;)

Thank you !
